# s = seconds, m = minutes, h = hours, d = days
# "->" separates the reason from the duration of the punishment
# You can append as many reasons for each punishment as you like

mute:
- "Mute reason 1 -> 1m"
- "Mute reason 2 -> 5m"
- "Mute reason 3 -> 10m"

kick:
- "Reason 1"
- "Reason 2"
- "Reason 3"

ban:
- "Ban reason 1 -> 1h"
- "Ban reason 2 -> 1d"
- "Ban reason 3 -> 7d"
