main: logan.punishgui.PunishPlugin
name: PunishGUI
version: 1.1
api-version: 1.13
author: Tre
depend: [Essentials]
commands:
  punishgui:
    description: Open the punishment GUI.
    permission: punishgui.punish
    usage: '§c/punish <player>'
  mutegui:
    description: Mute a player via GUI.
    permission: punishgui.mute
    usage: '§c/mutegui <player>'
  kickgui:
    description: Kick a player via GUI.
    permission: punishgui.kick
    usage: '§c/kickgui <player>'
  bangui:
    description: Ban a player via GUI.
    permission: punishgui.ban
    usage: '§c/bangui <player>'
  punishreload:
    description: Reload the punish configuration.
    permission: punishgui.reload
    usage: '§c/punishreload'