/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package src;

import org.junit.Test;
import static org.junit.Assert.*;

public class PunishPluginTest {
    @Test public void testAppHasAGreeting() {
        
    }
}
